apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapi
  template:
    metadata:
      labels:
        app: taskapi
    spec:
      containers:
      - name: taskapi
        image: taskapi:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
